### ISSUE TITLE
Problem if Dynatrace Javascript is Running

### ISSUE THREAD

**Issue by quackdor** [acoustic-analytics/UICaptureSDK-Modules#11]
If the Dynatrace Javascript library is running in an application, the Tealeaf Ajax Listener isn't able to record any ajax calls. Tested multiple times.   It doesn't prevent the Tealeaf POSTs from being received but is apparently preventing visibility from other Javascript.

Using 1.2.2,

**Comment by mpunjabi-aco** [comment]
In v1.2.2, the AjaxListener module checks to see if `XMLHttpRequest` and `fetch` is a native implementation. If a 3rd party script/polyfill is already overriding the native implementation then the AjaxListener module will not intercept these APIs. This is intentionally done in order to minimize any risk of faulty 3rd party implementations causing errors.

You can test this by removing the check which occurs on line [558-562](https://github.com/acoustic-analytics/UICaptureSDK-Modules/blob/759504fe6e6d892586449c90490372943ff747f3/AjaxListener/ajaxListener.js#L558) for `XMLHttpRequest` and line [566-568](https://github.com/acoustic-analytics/UICaptureSDK-Modules/blob/759504fe6e6d892586449c90490372943ff747f3/AjaxListener/ajaxListener.js#L566) for `fetch`

A better alternative is to load the UIC script first, such that the AjaxListener will interact with the native implementations.

Reference:
https://github.com/acoustic-analytics/UICaptureSDK-Modules/tree/master/AjaxListener#warning-important-note

**Comment by quackdor** [comment]
Unfortunately, the Dynatrace Oneagent forces its Javascript injection as the first Script on the page so we can't do anything about it.

**Comment by quackdor** [comment]
Based on your comment about removing the checks for native XHR and fetch would you say that the risk is minimal if non-existent if the 3rd party script is for sure not faulty?

**Comment by mpunjabi-aco** [comment]
> would you say that the risk is minimal if non-existent if the 3rd party script is for sure not faulty?

The risk cannot be non-existent but it can certainly be minimized by adequate testing and monitoring.

**Comment by mpunjabi-aco** [comment]
Added a [configuration flag](https://github.com/acoustic-analytics/UICaptureSDK-Modules/tree/master/AjaxListener#bypassing-the-safety-check-for-native-implementation-of-xhr-and-fetch) to bypass the safety check in module version `1.3.0`
